version: "3.9"
services:
  nginx:
    build:
      context: docker/nginx
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - php
      - mysql
    ports:
      - "${DOCKER_NGINX_HOST_PORT}:80"
    volumes:
      - ./:/app
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./:/app
  mysql:
    build:
      context: docker/mysql
    ports:
      - "${DOCKER_MYSQL_HOST_PORT}:3306"
    environment:
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
